#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
from math import radians, cos, sin, asin, sqrt
from termcolor import colored

# Import haversine from another file!

# def haversine(lon1, lat1, lon2, lat2):
#     """
#     Calculate the great circle distance between two points
#     on the earth (specified in decimal degrees)
#     """
#     # convert decimal degrees to radians
#     lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

#     # haversine formula
#     dlon = lon2 - lon1
#     dlat = lat2 - lat1
#     a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
#     c = 2 * asin(sqrt(a))
#     r = 6371  # Radius of earth in kilometers. Use 3956 for miles
#     return c * r


if __name__ == '__main__':
    description = 'Calculate the haversine distance between two points with the given coordinates.'
    parser = argparse.ArgumentParser(description=description)
    
    # ARGUMENTS
    parser.add_argument(
        '-c', '--coords',
        help = 'Takes longitude1, latitude1, longitude2, and latitude2',
        nargs = '+',
        required = False
    )

    args = parser.parse_args()
    lon1, lat1, lon2, lat2 = args.coords
    
    dist = haversine(float(lon1), float(lat1), float(lon2), float(lat2))
    
    print(colored('###### Distance ######', 'green'))
    print(colored(dist, 'red'))
